# Generated by Django 3.0.7 on 2020-06-06 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_portal', '0002_userapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.IntegerField(choices=[(1, 'SY-CSE-A'), (2, 'SY-CSE-B'), (3, 'TY-CSE-A'), (4, 'TY-CSE-B'), (5, 'SY-IT'), (6, 'TY-IT'), (7, 'SY-EnTC'), (8, 'TY-EnTC')], default=0)),
                ('status', models.IntegerField(choices=[(1, 'APPROVE'), (2, 'NOT APPROVED')], default=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserApproval',
        ),
    ]
